version: "3"

services:
  deconz:
    image: marthoc/deconz:latest
    container_name: deconz
    restart: always
    ports:
      - 5080:80
      - 5443:443
    volumes:
      - ./opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM1
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0





