version: "3"

services:
  strapi:
    container_name: strapi
    build:
      dockerfile: api/Dockerfile
      context: docker
    volumes:
    - ./app/:/usr/src/api/strapi-app
    ports:
      - 1337:1337
    env_file:
      - .env
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
