version: "3"

services:
  deconz:
    image: marthoc/deconz:latest
    container_name: deconz
    restart: always
    ports:
      - 5080:80 # GUI port
      - 5443:443 # WS port
    volumes:
      - ./opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    # The device listed here represents a Conbee II
    # The /dev/ID changes with the USB port that's used on the raspi
    # Easy way to find out which device id needs to be used:
    # Enter lsbusb into shell to see all usb devices (check if your device is connected)
    # Enter ls -l /dev/serial/by-id to see the correct device id
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0





