version: "3"

services:
  iobroker:
    restart: unless-stopped
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - 8089:8089
      - 8081:8081
      - 1883:1883
    volumes:
      - ./iobrokerdata:/opt/iobroker
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
